site_name: Personal Finance with AI
site_description: 'An AI driven course for teaching a practical introduction to personal finance for modern life.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/personal-finance/'
repo_url: 'https://github.com/dmccreary/personal-finance'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Course Description: course-description.md
  - Chapters:
    - Overview: chapters/index.md
    - Chapter 1 - Foundational Financial Concepts:
      - Introduction: chapters/01-foundational-financial-concepts/index.md
    - Chapter 2 - Banking & Cash Management:
      - Introduction: chapters/02-banking-and-cash-management/index.md
      - Regions of a Personal Check: chapters/02-banking-and-cash-management/regions-of-a-personal-check.md
    - Chapter 3 - Budgeting & Financial Planning:
      - Introduction: chapters/03-budgeting-and-financial-planning/index.md
    - Chapter 4 - Credit & Debt Management:
      - Introduction: chapters/04-credit-and-debt-management/index.md
      - The FICO Score: chapters/04-credit-and-debt-management/fico-score.md
      - Credit Card Bias: chapters/04-credit-and-debt-management/credit-card-bias.md
    - Chapter 5 - Saving & Investing:
      - Introduction: chapters/05-saving-and-investing/index.md
      - Index Funds: chapters/05-saving-and-investing/index-funds.md
    - Chapter 6 - Income & Taxes:
      - Introduction: chapters/06-income-and-taxes/index.md
    - Chapter 7 - Insurance & Risk Management:
      - Introduction: chapters/07-insurance-and-risk-management/index.md
    - Chapter 8 - Major Purchases & Loans:
      - Introduction: chapters/08-major-purchases-and-loans/index.md
    - Chapter 9 - Consumer Protection & Financial Security:
      - Introduction: chapters/09-consumer-protection-and-financial-security/index.md
    - Chapter 10 - College & Education Planning:
      - Introduction: chapters/10-college-and-education-planning/index.md
    - Chapter 11 - Career Planning & Income:
      - Introduction: chapters/11-career-planning-and-income/index.md
    - Chapter 12 - Retirement & Long-term Planning:
      - Introduction: chapters/12-retirement-and-long-term-planning/index.md
      - Social Security Planner: chapters/12-retirement-and-long-term-planning/social-security-planner.md
  - Learning Graph:
    - Overview: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
  - Stories:
    - Introduction: stories/index.md
    - Passive Investing: stories/passive-investing.md
    - Selection Bias: stories/selection-bias/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Bloom Taxonomy: prompts/02-bloom-taxonomy.md
    - Concept Enumeration: prompts/04-concept-enumeration.md
    - Concept Dependency: prompts/06-concept-dependency.md
    - Concept Taxonomy: prompts/08-concept-taxonomy.md
    - Concept Classification: prompts/10-concept-classification.md
    - Glossary: prompts/12-glossary-prompt.md
    - List of MicroSims: prompts/14-list-of-microsims.md
    - US High School Topics: prompts/03-us-high-school-topics.md
    - Storytelling: prompts/13-storytelling.md
    - Cover Image: prompts/15-cover-image.md
  - MicroSims:
    - Introduction: sims/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Compound Interest Visualizer: sims/compound-interest-visualizer/index.md
    - College Loan Payback: sims/college-loan-payback/index.md
    - Active vs Indexed Funds: sims/active-vs-indexed/index.md
    - Social Security: sims/social-security-crossover/index.md
    - FICO Score Spectrum: sims/fico-score-spectrum/index.md
    - Inflation Rate: sims/inflation-rate/index.md
    - Interest Rate: sims/interest-rate/index.md
    - Stock Market Historical Returns: sims/stock-market-returns/index.md
    - US Treasury Bills: sims/t-bills/index.md
    - Yield Curve: sims/yield-curve/index.md

  - Resources:
    - Introduction: resources/index.md
    - Minnesota Personal Finance Legislation: resources/mn-legislation.md
    - Smart Money for Young People: resources/smart-money-for-young-people.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Feedback: feedback.md
  - License: license.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'green'
    accent: 'yellow'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
  - social_override
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
copyright: Copyright &copy; 2025 Dan McCreary. Licensed under <a href="license/">CC BY-NC-SA 4.0</a> for non-commercial use.
extra:
  analytics:
    provider: google
    property: G-M7190QC8H7